[template]
cargo_generate_version = ">=0.9.0"
description = "A Pico2 project template with Embassy or RP-HAL"

[hooks]
pre = ["cargo-generate/prehook.rhai"]

[placeholders.hal]
type = "string"
prompt = "Which HAL?"
choices = ["embassy", "rp-hal"]
default = "embassy"
